In [39]:
url = "https://www.flipkart.com/search?q=laptop&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page=1"

In [41]:
Data = requests.get(url)
Data

In [42]:
data_content = Data.content 
data_content

b'<!doctype html><html lang="en"><head><link href="https://rukminim2.flixcart.com" rel="preconnect"/><link rel="stylesheet" href="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/css/app_modules.chunk.c48a12.css"/><link rel="stylesheet" href="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/css/app.chunk.066267.css"/><meta http-equiv="Content-type" content="text/html; charset=utf-8"/><meta http-equiv="X-UA-Compatible" content="IE=Edge"/><meta property="fb:page_id" content="102988293558"/><meta property="fb:admins" content="658873552,624500995,100000233612389"/><link rel="shortcut icon" href="https://static-assets-web.flixcart.com/www/promos/new/20150528-140547-favicon-retina.ico"/><link type="application/opensearchdescription+xml" rel="search" href="/osdd.xml?v=2"/><meta property="og:type" content="website"/><meta name="og_site_name" property="og:site_name" content="Flipkart.com"/><link rel="apple-touch-icon" sizes="57x57" href="/apple-touch-icon-57x57.png"/><link rel="apple-touch-icon" sizes="72x72" href="/apple-touch-icon-72x72.png"/><link rel="apple-touch-icon" sizes="114x114" href="/apple-touch-icon-114x114.png"/><link rel="apple-touch-icon" sizes="144x144" href="/apple-touch-icon-144x144.png"/><link rel="apple-touch-icon" href="/apple-touch-icon-57x57.png"/><meta name="twitter:card" content="app"><meta name="twitter:site" content="@flipkart"><meta name="twitter:creator" content="@flipkart"><meta name="twitter:title" content="Laptop- Buy Products Online at Best Price in India - All Categories | Flipkart.com"><meta name="twitter:description" content="Shop for electronics, apparels & more using our Flipkart app Free shipping & COD."><meta name="twitter:app:country" content="in"><meta name="al:ios:app_name" content="Flipkart"><meta name="al:ios:app_store_id" content="742044692"><meta name="twitter:app:name:iphone" content="Flipkart"><meta name="twitter:app:id:iphone" content="742044692"><meta name="twitter:app:url:iphone" content="http://dl.flipkart.com/dl/home?"><meta name="twitter:app:name:ipad" content="Flipkart"><meta name="twitter:app:id:ipad" content="742044692"><meta name="twitter:app:url:ipad" content="http://dl.flipkart.com/dl/home?"><meta name="twitter:app:name:googleplay" content="Flipkart"><meta name="twitter:app:id:googleplay" content="com.flipkart.android"><meta name="twitter:app:url:googleplay" content="http://dl.flipkart.com/dl/home?"><style>#container {\n\t\t\theight: 100%;\n\t\t}</style>  <link rel="stylesheet" href="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/css/Browse.chunk.83db80.css"/><title>Laptop- Buy Products Online at Best Price in India - All Categories | Flipkart.com</title><meta name="og_title" property="og:title" content="Laptop- Buy Products Online at Best Price in India - All Categories | Flipkart.com"/><meta name="Keywords" content="Laptop"/> <meta name="Description" content="Laptop- Buy Products Online at Best Price in India. India&#x27;s Leading E-commerce Company - Free Home Delivery - All Categories | Flipkart.com"/><meta property="og:description" content="Laptop- Buy Products Online at Best Price in India. India&#x27;s Leading E-commerce Company - Free Home Delivery - All Categories | Flipkart.com"/>       <meta name="msvalidate.01" content="F4EEB3A0AFFDD385992A06E6920C0AC3"/> <!--[if IE 9 ]>\n\t<script nonce="2049021680974061606">\n\t\twindow.browserVersion = \'IE9\';\n\t\tdocument.documentElement.className += \' ie9\';\n\t</script>\n\t<![endif]--><!--[if !IE]><!--><script nonce="2049021680974061606">if (/*@cc_on!@*/false) {\n\t\t\twindow.browserVersion = \'IE10\';\n\t\t\tdocument.documentElement.className += \' ie10\';\n\t\t}</script><!--<![endif]-->   <link href="https://www.flipkart.com/search?q&#x3D;laptop&amp;otracker&#x3D;search&amp;otracker1&#x3D;search&amp;marketplace&#x3D;FLIPKART&amp;as-show&#x3D;on&amp;as&#x3D;off&amp;page&#x3D;2" id="next-page-link-tag" rel="next"><script nonce="2049021680974061606">!function(){if("PerformancePaintTiming" in window){var e=window.__perf={e:[]};e.o=new PerformanceObserver(function(n){e.e=e.e.concat(n.getEntries())});try{e.o.observe({entryTypes:["paint"]})}catch(e){}}}();\n\n\t\tif (requestAnimationFrame && performance && performance.mark) {\n\t\t\trequestAnimationFrame(function () {\n\t\t\t\twindow.first_paint = performance.now();\n\t\t\t\tperformance.mark("first_paint");\n\t\t\t});\n\t\t}\n\n        // web-vitals polyfill for FID\n        !function(n,e){var t,o,i,c=[],f={passive:!0,capture:!0},r=new Date,a="pointerup",u="pointercancel";function p(n,c){t||(t=c,o=n,i=new Date,w(e),s())}function s(){o>=0&&o<i-r&&(c.forEach(function(n){n(o,t)}),c=[])}function l(t){if(t.cancelable){var o=(t.timeStamp>1e12?new Date:performance.now())-t.timeStamp;"pointerdown"==t.type?function(t,o){function i(){p(t,o),r()}function c(){r()}function r(){e(a,i,f),e(u,c,f)}n(a,i,f),n(u,c,f)}(o,t):p(o,t)}}function w(n){["click","mousedown","keydown","touchstart","pointerdown"].forEach(function(e){n(e,l,f)})}w(n),self.perfMetrics=self.perfMetrics||{},self.perfMetrics.onFirstInputDelay=function(n){c.push(n),s()}}(addEventListener,removeEventListener);</script><script async src="https://www.googletagmanager.com/gtag/js?id=AW-594691041"></script><script nonce="2049021680974061606">window.dataLayer = window.dataLayer || [];\n\t\tfunction gtag(){dataLayer.push(arguments)};\n\t\tgtag(\'js\', new Date());\n\n\t\tconst pageUri = window.location.pathname;\n    \t\tif (pageUri && pageUri.includes(\'/travel\')) {\n\t\t\tgtag(\'config\', \'AW-16596706887\');\n\t\t}</script></head><body><div id="container"><div><div class="krHvwW"><div class="J+HqMZ"><div class="LOe-Xr"></div><div class="Ja1j8k"><div class="ngOQ7L"><div class="F9+fd2"><a href="/"><img width="75" src="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/img/flipkart-plus_8d85f4.png" alt="Flipkart" title="Flipkart" class="W5mR4e"/></a><a class="MwbhDR" href="/plus">Explore<!-- --> <span class="s4NJ5L">Plus</span><img width="10" src="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/img/plus_aef861.png"/></a></div></div><div class="kRd8Cs"><form class="Hy6F9O header-form-search" action="/search" method="GET"><div class="col-12-12 BnmXvV"><div class="MoPwtI"><input class="zDPmFV" type="text" title="Search for products, brands and more" name="q" autoComplete="off" placeholder="Search for products, brands and more" value="laptop"/></div><button class="MJG8Up" type="submit"><svg width="20" height="20" viewBox="0 0 17 18" class="" xmlns="http://www.w3.org/2000/svg"><g fill="#2874F1" fill-rule="evenodd"><path class="EwE-Fa" d="m11.618 9.897l4.225 4.212c.092.092.101.232.02.313l-1.465 1.46c-.081.081-.221.072-.314-.02l-4.216-4.203"></path><path class="EwE-Fa" d="m6.486 10.901c-2.42 0-4.381-1.956-4.381-4.368 0-2.413 1.961-4.369 4.381-4.369 2.42 0 4.381 1.956 4.381 4.369 0 2.413-1.961 4.368-4.381 4.368m0-10.835c-3.582 0-6.486 2.895-6.486 6.467 0 3.572 2.904 6.467 6.486 6.467 3.582 0 6.486-2.895 6.486-6.467 0-3.572-2.904-6.467-6.486-6.467"></path></g></svg></button><input type="hidden" name="otracker" value="search"/><input type="hidden" name="otracker1" value="search"/><input type="hidden" name="marketplace" value="FLIPKART"/><input type="hidden" name="as-show" value="off"/><input type="hidden" name="as" value="off"/></div><ul class="col-12-12 bbjHWC"></ul></form></div><div class="RbF1Du UB4mMK"><div class="UL9nZx"><div class="tP+nZg _2E9UgX"><div><a class="wsejfv" href="/account/login?ret=/search%3Fq%3Dlaptop%26otracker%3Dsearch%26otracker1%3Dsearch%26marketplace%3DFLIPKART%26as-show%3Don%26as%3Doff%26page%3D1">Login</a></div></div></div></div><div class="RbF1Du"><a href="https://seller.flipkart.com/sell-online/?utm_source=fkwebsite&amp;utm_medium=websitedirect" class="CDJO0-"><span>Become a Seller</span></a></div><div class="RbF1Du"><div class="UL9nZx"><div class="tP+nZg _2E9UgX"><div><div class="_3ZeUN+"> <!-- -->More<!-- --> </div></div></div><svg width="4.7" height="8" viewBox="0 0 16 27" xmlns="http://www.w3.org/2000/svg" class="Wto0b0"><path d="M16 23.207L6.11 13.161 16 3.093 12.955 0 0 13.161l12.955 13.161z" fill="#fff" class="-dC5Le"></path></svg></div></div><div class="RbF1Du"><div class="tP+nZg"><div class="cjMG1q"><a class="_9Wy27C" href="/viewcart?exploreMode=true&amp;preference=FLIPKART"><svg class="GAbRIN" width="14" height="14" viewBox="0 0 16 16" xmlns="http://www.w3.org/2000/svg"><path class="cziJ98" d="M15.32 2.405H4.887C3 2.405 2.46.805 2.46.805L2.257.21C2.208.085 2.083 0 1.946 0H.336C.1 0-.064.24.024.46l.644 1.945L3.11 9.767c.047.137.175.23.32.23h8.418l-.493 1.958H3.768l.002.003c-.017 0-.033-.003-.05-.003-1.06 0-1.92.86-1.92 1.92s.86 1.92 1.92 1.92c.99 0 1.805-.75 1.91-1.712l5.55.076c.12.922.91 1.636 1.867 1.636 1.04 0 1.885-.844 1.885-1.885 0-.866-.584-1.593-1.38-1.814l2.423-8.832c.12-.433-.206-.86-.655-.86" fill="#fff"></path></svg><span>Cart</span></a></div></div></div></div><div class="LOe-Xr"></div></div><div class="DlQjC4"></div></div><div class="_5M58Mb"></div><div class="nt6sNV JxFEK3 _48O0EI"><div class="DOjaWF YJG4Cf"><div class="DOjaWF gdgoEp col-2-12" style="flex:0 0 280px;max-width:280px;padding:0px 10px 0px 0px"><div class="DOjaWF gdgoEp col-12-12"><div class="cPHDOP col-12-12"><div class="_0BvurA"><section class="pgRLLn _2OLUF3"><div class="_3Owiq+"><div class="rgHxCQ"><span>Filters</span></div></div></section><div class="GSeM5C"><section class="Iu4qXa"><div class="WCyB2K"><span>CATEGORIES</span></div><div><div class="esFpML"><span><svg width="10" height="10" viewBox="0 0 16 27" xmlns="http://www.w3.org/2000/svg" class="IZmjtf"><path d="M16 23.207L6.11 13.161 16 3.093 12.955 0 0 13.161l12.955 13.161z" fill="#fff" class="P3pAQJ"></path></svg></span><a class="k17cBJ WyLc0s" title="Computers" href="/computers/pr?sid=6bo&amp;q=laptop&amp;otracker=categorytree">Computers</a></div></div><div><div class="esFpML"><span><svg width="10" height="10" viewBox="0 0 16 27" xmlns="http://www.w3.org/2000/svg" class="IZmjtf"><path d="M16 23.207L6.11 13.161 16 3.093 12.955 0 0 13.161l12.955 13.161z" fill="#fff" class=""></path></svg></span><a class="hEjLuS WyLc0s" title="Laptops" href="/laptops/pr?sid=6bo,b5g&amp;q=laptop&amp;otracker=categorytree">Laptops</a></div></div></section></div><section class="-5qqlC _2OLUF3"><div class="FtQCb2 _3Owiq+"><div class="fxf7w6 rgHxCQ">Brand</div><svg width="16" height="27" viewBox="0 0 16 27" xmlns="http://www.w3.org/2000/svg" class="ukzDZP"><path d="M16 23.207L6.11 13.161 16 3.093 12.955 0 0 13.161l12.955 13.161z" fill="#fff" class="SV+H35"></path></svg></div></section><section class="-5qqlC _2OLUF3"><div class="FtQCb2 _3Owiq+"><div class="fxf7w6 rgHxCQ">Discount</div><svg width="16" height="27" viewBox="0 0 16 27" xmlns="http://www.w3.org/2000/svg" class="ukzDZP"><path d="M16 23.207L6.11 13.161 16 3.093 12.955 0 0 13.161l12.955 13.161z" fill="#fff" class="SV+H35"></path></svg></div></section><section class="-5qqlC _2OLUF3"><div class="FtQCb2 _3Owiq+"><div class="fxf7w6 rgHxCQ">Processor</div><svg width="16" height="27" viewBox="0 0 16 27" xmlns="http://www.w3.org/2000/svg" class="ukzDZP rZzKt4"><path d="M16 23.207L6.11 13.161 16 3.093 12.955 0 0 13.161l12.955 13.161z" fill="#fff" class="SV+H35"></path></svg></div><div class="SDsN9S"><div class="bs1+1t"><div class="Cj5b5T"><svg width="20" height="20" viewBox="0 0 17 18" class="zmbstL" xmlns="http://www.w3.org/2000/svg"><g fill="#2874F1" fill-rule="evenodd"><path class="JVQyl9" d="m11.618 9.897l4.225 4.212c.092.092.101.232.02.313l-1.465 1.46c-.081.081-.221.072-.314-.02l-4.216-4.203"></path><path class="JVQyl9" d="m6.486 10.901c-2.42 0-4.381-1.956-4.381-4.368 0-2.413 1.961-4.369 4.381-4.369 2.42 0 4.381 1.956 4.381 4.369 0 2.413-1.961 4.368-4.381 4.368m0-10.835c-3.582 0-6.486 2.895-6.486 6.467 0 3.572 2.904 6.467 6.486 6.467 3.582 0 6.486-2.895 6.486-6.467 0-3.572-2.904-6.467-6.486-6.467"></path></g></svg><input type="text" class="XPD6hh" placeholder="Search Processor" value=""/></div><div class="ewzVkT _3DvUAf" title="Core i5"><div class="QCKZip hpLdC3"><label class="tJjCVx _3DvUAf"><input type="checkbox" class="vn9L2C" readonly=""/><div class="XqNaEv"></div><div class="_6i1qKy">Core i5</div></label></div></div><div class="ewzVkT _3DvUAf" title="Core i3"><div class="QCKZip hpLdC3"><label class="tJjCVx _3DvUAf"><input type="checkbox" class="vn9L2C" readonly=""/><div class="XqNaEv"></div><div class="_6i1qKy">Core i3</div></label></div></div><div class="ewzVkT _3DvUAf" title="Core i7"><div class="QCKZip hpLdC3"><label class="tJjCVx _3DvUAf"><input type="checkbox" class="vn9L2C" readonly=""/><div class="XqNaEv"></div><div class="_6i1qKy">Core i7</div></label></div></div><div class="ewzVkT _3DvUAf" title="Ryzen 7 Quad Core"><div class="QCKZip hpLdC3"><label class="tJjCVx _3DvUAf"><input type="checkbox" class="vn9L2C" readonly=""/><div class="XqNaEv"></div><div class="_6i1qKy">Ryzen 7 Quad Core</div></label></div></div><div class="ewzVkT _3DvUAf" title="Ryzen 5 Quad Core"><div class="QCKZip hpLdC3"><label class="tJjCVx _3DvUAf"><input type="checkbox" class="vn9L2C" readonly=""/><div class="XqNaEv"></div><div class="_6i1qKy">Ryzen 5 Quad Core</div></label></div></div><div class="ewzVkT _3DvUAf" title="Core i9"><div class="QCKZip hpLdC3"><label class="tJjCVx _3DvUAf"><input type="checkbox" class="vn9L2C" readonly=""/><div class="XqNaEv"></div><div class="_6i1qKy">Core i9</div></label></div></div></div><div class="e+xvXX KvHRYS"><span>63 MORE</span></div></div></section><section class="-5qqlC _2OLUF3"><div class="FtQCb2 _3Owiq+"><div class="fxf7w6 rgHxCQ">RAM Capacity</div><svg width="16" height="27" viewBox="0 0 16 27" xmlns="http://www.w3.org/2000/svg" class="ukzDZP"><path d="M16 23.207L6.11 13.161 16 3.093 12.955 0 0 13.161l12.955 13.161z" fill="#fff" class="SV+H35"></path></svg></div></section><section class="FR+9+z _2OLUF3"><div class="WNK7UT _3Owiq+"><div class="RCE7R3 rgHxCQ"><span>Price</span></div></div><div class="rkYFq7"><div class="gFZVDw"><div class="vVygGr" style="height:0;width:0"></div><div class="vVygGr" style="height:0;width:0"></div><div class="vVygGr" style="height:0;width:0"></div><div class="vVygGr" style="height:0;width:0"></div><div class="vVygGr" style="height:0;width:0"></div><div class="vVygGr" style="height:0;width:0"></div></div></div><div class="-suZGK"><div class="Oyj7AF"><div class="iToJ4v Kaqq1s"><div class="PYKUdo"></div></div><div class="iToJ4v D0puJn"><div class="PYKUdo"></div></div><div class="hZmZbn"></div><div class="hZmZbn AQNm5W"></div></div><div class="C+PahU"><div class="JxsWRk" style="width:undefinedpx">.</div><div class="JxsWRk" style="width:undefinedpx">.</div><div class="JxsWRk" style="width:undefinedpx">.</div><div class="JxsWRk" style="width:undefinedpx">.</div><div class="JxsWRk" style="width:undefinedpx">.</div><div class="JxsWRk" style="width:undefinedpx">.</div><div class="JxsWRk" style="width:0px">.</div></div></div><div class="BXgIa-"><div class="suthUA"><select class="Gn+jFg"><option value="Min" class="_0vP2OD" selected="">Min</option><option value="20000" class="_0vP2OD">\xe2\x82\xb920000</option><option value="40000" class="_0vP2OD">\xe2\x82\xb940000</option><option value="50000" class="_0vP2OD">\xe2\x82\xb950000</option><option value="60000" class="_0vP2OD">\xe2\x82\xb960000</option><option value="75000" class="_0vP2OD">\xe2\x82\xb975000</option></select></div><div class="mhoEL5">to</div><div class="tKgS7w"><select class="Gn+jFg"><option value="20000" class="_0vP2OD">\xe2\x82\xb920000</option><option value="40000" class="_0vP2OD">\xe2\x82\xb940000</option><option value="50000" class="_0vP2OD">\xe2\x82\xb950000</option><option value="60000" class="_0vP2OD">\xe2\x82\xb960000</option><option value="75000" class="_0vP2OD">\xe2\x82\xb975000</option><option value="Max" class="_0vP2OD" selected="">\xe2\x82\xb975000+</option></select></div></div></section><section class="-5qqlC _2OLUF3"><div class="FtQCb2 _3Owiq+"><div class="fxf7w6 rgHxCQ">Processor Generation</div><svg width="16" height="27" viewBox="0 0 16 27" xmlns="http://www.w3.org/2000/svg" class="ukzDZP"><path d="M16 23.207L6.11 13.161 16 3.093 12.955 0 0 13.161l12.955 13.161z" fill="#fff" class="SV+H35"></path></svg></div></section><section class="-5qqlC _2OLUF3"><div class="FtQCb2 _3Owiq+"><div class="fxf7w6 rgHxCQ">Ram Type</div><svg width="16" height="27" viewBox="0 0 16 27" xmlns="http://www.w3.org/2000/svg" class="ukzDZP"><path d="M16 23.207L6.11 13.161 16 3.093 12.955 0 0 13.161l12.955 13.161z" fill="#fff" class="SV+H35"></path></svg></div></section><section class="-5qqlC _2OLUF3"><div class="FtQCb2 _3Owiq+"><div class="fxf7w6 rgHxCQ">Offers</div><svg width="16" height="27" viewBox="0 0 16 27" xmlns="http://www.w3.org/2000/svg" class="ukzDZP rZzKt4"><path d="M16 23.207L6.11 13.161 16 3.093 12.955 0 0 13.161l12.955 13.161z" fill="#fff" class="SV+H35"></path></svg></div><div class="SDsN9S"><div class="bs1+1t"><div class="ewzVkT _3DvUAf" title="Special Price"><div class="QCKZip hpLdC3"><label class="tJjCVx _3DvUAf"><input type="checkbox" class="vn9L2C" readonly=""/><div class="XqNaEv"></div><div class="_6i1qKy">Special Price</div></label></div></div><div class="ewzVkT _3DvUAf" title="No Cost EMI"><div class="QCKZip hpLdC3"><label class="tJjCVx _3DvUAf"><input type="checkbox" class="vn9L2C" readonly=""/><div class="XqNaEv"></div><div class="_6i1qKy">No Cost EMI</div></label></div></div></div></div></section><section class="-5qqlC _2OLUF3"><div class="FtQCb2 _3Owiq+"><div class="fxf7w6 rgHxCQ">SSD Capacity</div><svg width="16" height="27" viewBox="0 0 16 27" xmlns="http://www.w3.org/2000/svg" class="ukzDZP"><path d="M16 23.207L6.11 13.161 16 3.093 12.955 0 0 13.161l12.955 13.161z" fill="#fff" class="SV+H35"></path></svg></div></section><section class="-5qqlC _2OLUF3"><div class="FtQCb2 _3Owiq+"><div class="fxf7w6 rgHxCQ">RAM Capacity</div><svg width="16" height="27" viewBox="0 0 16 27" xmlns="http://www.w3.org/2000/svg" class="ukzDZP"><path d="M16 23.207L6.11 13.161 16 3.093 12.955 0 0 13.161l12.955 13.161z" fill="#fff" class="SV+H35"></path></svg></div></section><section class="-5qqlC _2OLUF3"><div class="FtQCb2 _3Owiq+"><div class="fxf7w6 rgHxCQ">Usage</div><svg width="16" height="27" viewBox="0 0 16 27" xmlns="http://www.w3.org/2000/svg" class="ukzDZP"><path d="M16 23.207L6.11 13.161 16 3.093 12.955 0 0 13.161l12.955 13.161z" fill="#fff" class="SV+H35"></path></svg></div></section><section class="-5qqlC _2OLUF3"><div class="FtQCb2 _3Owiq+"><div class="fxf7w6 rgHxCQ">Dedicated Graphics Memory</div><svg width="16" height="27" viewBox="0 0 16 27" xmlns="http://www.w3.org/2000/svg" class="ukzDZP"><path d="M16 23.207L6.11 13.161 16 3.093 12.955 0 0 13.161l12.955 13.161z" fill="#fff" class="SV+H35"></path></svg></div></section><section class="-5qqlC _2OLUF3"><div class="FtQCb2 _3Owiq+"><div class="fxf7w6 rgHxCQ">Type</div><svg width="16" height="27" viewBox="0 0 16 27" xmlns="http://www.w3.org/2000/svg" class="ukzDZP"><path d="M16 23.207L6.11 13.161 16 3.093 12.955 0 0 13.161l12.955 13.161z" fill="#fff" class="SV+H35"></path></svg></div></section><section class="-5qqlC _2OLUF3"><div class="FtQCb2 _3Owiq+"><div class="fxf7w6 rgHxCQ">Screen Size</div><svg width="16" height="27" viewBox="0 0 16 27" xmlns="http://www.w3.org/2000/svg" class="ukzDZP"><path d="M16 23.207L6.11 13.161 16 3.093 12.955 0 0 13.161l12.955 13.161z" fill="#fff" class="SV+H35"></path></svg></div></section><section class="-5qqlC _2OLUF3"><div class="FtQCb2 _3Owiq+"><div class="fxf7w6 rgHxCQ">Operating System</div><svg width="16" height="27" viewBox="0 0 16 27" xmlns="http://www.w3.org/2000/svg" class="ukzDZP"><path d="M16 23.207L6.11 13.161 16 3.093 12.955 0 0 13.161l12.955 13.161z" fill="#fff" class="SV+H35"></path></svg></div></section><section class="-5qqlC _2OLUF3"><div class="FtQCb2 _3Owiq+"><div class="fxf7w6 rgHxCQ">Weight</div><svg width="16" height="27" viewBox="0 0 16 27" xmlns="http://www.w3.org/2000/svg" class="ukzDZP"><path d="M16 23.207L6.11 13.161 16 3.093 12.955 0 0 13.

In [43]:
from bs4 import BeautifulSoup
soup = BeautifulSoup(data_content)

In [44]:
soup

<!DOCTYPE html>
<html lang="en"><head><link href="https://rukminim2.flixcart.com" rel="preconnect"/><link href="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/css/app_modules.chunk.c48a12.css" rel="stylesheet"/><link href="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/css/app.chunk.066267.css" rel="stylesheet"/><meta content="text/html; charset=utf-8" http-equiv="Content-type"/><meta content="IE=Edge" http-equiv="X-UA-Compatible"/><meta content="102988293558" property="fb:page_id"/><meta content="658873552,624500995,100000233612389" property="fb:admins"/><link href="https://static-assets-web.flixcart.com/www/promos/new/20150528-140547-favicon-retina.ico" rel="shortcut icon"/><link href="/osdd.xml?v=2" rel="search" type="application/opensearchdescription+xml"/><meta content="website" property="og:type"/><meta content="Flipkart.com" name="og_site_name" property="og:site_name"/><link href="/apple-touch-icon-57x57.png" rel="apple-touch-icon" sizes="57x57"/><link href="/apple-touch-icon-72x72.png" rel="apple-touch-icon" sizes="72x72"/><link href="/apple-touch-icon-114x114.png" rel="apple-touch-icon" sizes="114x114"/><link href="/apple-touch-icon-144x144.png" rel="apple-touch-icon" sizes="144x144"/><link href="/apple-touch-icon-57x57.png" rel="apple-touch-icon"/><meta content="app" name="twitter:card"/><meta content="@flipkart" name="twitter:site"/><meta content="@flipkart" name="twitter:creator"/><meta content="Laptop- Buy Products Online at Best Price in India - All Categories | Flipkart.com" name="twitter:title"/><meta content="Shop for electronics, apparels &amp; more using our Flipkart app Free shipping &amp; COD." name="twitter:description"/><meta content="in" name="twitter:app:country"/><meta content="Flipkart" name="al:ios:app_name"/><meta content="742044692" name="al:ios:app_store_id"/><meta content="Flipkart" name="twitter:app:name:iphone"/><meta content="742044692" name="twitter:app:id:iphone"/><meta content="http://dl.flipkart.com/dl/home?" name="twitter:app:url:iphone"/><meta content="Flipkart" name="twitter:app:name:ipad"/><meta content="742044692" name="twitter:app:id:ipad"/><meta content="http://dl.flipkart.com/dl/home?" name="twitter:app:url:ipad"/><meta content="Flipkart" name="twitter:app:name:googleplay"/><meta content="com.flipkart.android" name="twitter:app:id:googleplay"/><meta content="http://dl.flipkart.com/dl/home?" name="twitter:app:url:googleplay"/><style>#container {
			height: 100%;
		}</style> <link href="//static-assets-web.flixcart.com/fk-p-linchpin-web/fk-cp-zion/css/Browse.chunk.83db80.css" rel="stylesheet"/><title>Laptop- Buy Products Online at Best Price in India - All Categories | Flipkart.com</title><meta content="Laptop- Buy Products Online at Best Price in India - All Categories | Flipkart.com" name="og_title" property="og:title"/><meta content="Laptop" name="Keywords"/> <meta content="Laptop- Buy Products Online at Best Price in India. India's Leading E-commerce Company - Free Home Delivery - All Categories | Flipkart.com" name="Description"/><meta content="Laptop- Buy Products Online at Best Price in India. India's Leading E-commerce Company - Free Home Delivery - All Categories | Flipkart.com" property="og:description"/> <meta content="F4EEB3A0AFFDD385992A06E6920C0AC3" name="msvalidate.01"/> <!--[if IE 9 ]>
	<script nonce="2049021680974061606">
		window.browserVersion = 'IE9';
		document.documentElement.className += ' ie9';
	</script>
	<![endif]--><!--[if !IE]><!--><script nonce="2049021680974061606">if (/*@cc_on!@*/false) {
			window.browserVersion = 'IE10';
			document.documentElement.className += ' ie10';
		}</script><!--<![endif]--> <link href="https://www.flipkart.com/search?q=laptop&amp;otracker=search&amp;otracker1=search&amp;marketplace=FLIPKART&amp;as-show=on&amp;as=off&amp;page=2" id="next-page-link-tag" rel="next"/><script nonce="2049021680974061606">!function(){if("PerformancePaintTiming" in window){var e=window.__perf={e:[]};e.o=new PerformanceObserver(function(n){e.e=e.e.concat(n.getEntries())});try{e.o.observe({entryTypes:["paint"]})}catch(e){}}}();

		if (requestAnimationFrame && performance && performance.mark) {
			requestAnimationFrame(function () {
				window.first_paint = performance.now();
				performance.mark("first_paint");
			});
		}

        // web-vitals polyfill for FID
        !function(n,e){var t,o,i,c=[],f={passive:!0,capture:!0},r=new Date,a="pointerup",u="pointercancel";function p(n,c){t||(t=c,o=n,i=new Date,w(e),s())}function s(){o>=0&&o<i-r&&(c.forEach(function(n){n(o,t)}),c=[])}function l(t){if(t.cancelable){var o=(t.timeStamp>1e12?new Date:performance.now())-t.timeStamp;"pointerdown"==t.type?function(t,o){function i(){p(t,o),r()}function c(){r()}function r(){e(a,i,f),e(u,c,f)}n(a,i,f),n(u,c,f)}(o,t):p(o,t)}}function w(n){["click","mousedown","keydown","touchstart","pointerdown"].forEach(function(e){n(e,l,f)})}w(n),self.perfMetrics=self.perfMetrics||{},self.perfMetrics.onFirstInputDelay=function(n){c.push(n),s()}}(addEventListener,removeEventListener);</script><script async="" src="https://www.googletagmanager.com/gtag/js?id=AW-594691041"></script><script nonce="2049021680974061606">window.dataLayer = window.dataLayer || [];
		function gtag(){dataLayer.push(arguments)};
		gtag('js', new Date());

		const pageUri = window.location.pathname;
    		if (pageUri && pageUri.includes('/travel')) {
			gtag('config', 'AW-16596706887');

In [52]:
title = []
for i in soup.find_all("div",class_= "KzDlHZ"):
    title.append(i.text)

In [53]:
title

['CHUWI Intel Core i3 10th Gen 10100Y - (8 GB/256 GB SSD/Windows 11 Home) CoreBook X Grey Laptop',
 'CHUWI Intel Core i5 12th Gen 12450H - (16 GB/512 GB SSD/Windows 11 Home) CoreBook X_Pro Laptop',
 'Acer 3 Years Warranty Aspire 3 (2025) Intel Core i3 13th Gen 1305U - (16 GB/512 GB SSD/Windows 11 Home...',
 'Acer Aspire 3 Intel Celeron Dual Core - (8 GB/128 GB SSD/Windows 11 Home) A311-45 Thin and Light Lapto...',
 'Acer Aspire 3 (2025) Intel Core i5 13th Gen 1334U - (16 GB/512 GB SSD/Windows 11 Home) Aspire 3 A325-5...',
 'CHUWI Intel Core i3 12th Gen Intel Core i3-1215U - (12 GB/512 GB SSD/Windows 11 Home) FreeBook 2 in 1 ...',
 'Acer Aspire 3 Intel Core i3 12th Gen 1215U - (8 GB/512 GB SSD/Windows 11 Home) A324-51 Thin and Light ...',
 'HP 15 (2025) AMD Ryzen 3 Quad Core 7320U - (16 GB/512 GB SSD/Windows 11 Home) 15 Thin and Light Laptop',
 'Acer Aspire AMD Ryzen 5 Hexa Core 7430U - (16 GB/1 TB SSD/Windows 11 Home) AS15-42 Thin and Light Lapt...',
 'HP AMD Ryzen 5 Hexa Core 7530U - (8 GB/512 GB SSD/Windows 11 Home) 15-fc0388AU Thin and Light Laptop',
 'Acer Professional AMD Ryzen 3 Quad Core 7th Gen 7330U With Turbo Boost - (16 GB/512 GB SSD/Windows 11 ...',
 'Primebook 2 Max (2025) in-Built AI MediaTek Helio G99 (MT8781) - (8 GB/256 GB/Android 15) PBG9915256#4...',
 'Acer Aspire 3 Intel Celeron Dual Core N4500 - (8 GB/512 GB SSD/Windows 11 Home) A325-45 Thin and Light...',
 'Acer Aspire 3 Intel Celeron Dual Core - (8 GB/512 GB SSD/Windows 11 Home) A311-45 Thin and Light Lapto...',
 'ASUS Vivobook 15, with Backlit Keyboard, Intel Core i3 13th Gen 1315U - (16 GB/512 GB SSD/Windows 11 H...',
 'HP 15 (2024) AMD Ryzen 3 Quad Core 7320U - (8 GB/512 GB SSD/Windows 11 Home) 15-fc0500AU / 15-fc0154AU...',
 "Lenovo IdeaPad Slim 3 Backlit Keyboard with MSO'2024 Intel Core i5 13th Gen 13420H - (16 GB/512 GB SSD...",
 'Lenovo IdeaPad Slim 3 Backlit Intel Core i5 12th Gen 12450H - (16 GB/512 GB SSD/Windows 11 Home) 15IAH...',
 'DELL Inspiron 5440 (2025) Intel Core i3 13th Gen 1305U - (16 GB/512 GB SSD/Windows 11 Home) Inspiron 5...',
 'Samsung Galaxy Book4 Metal Intel Core i3 13th Gen 1315U - (8 GB/512 GB SSD/Windows 11 Home) NP750XGJ-L...',
 'HP Laptop Intel Core i3 13th Gen 1315U - (8 GB/512 GB SSD/Windows 11 Home) 15-fd0129TU / 15-fd0568TU T...',
 'Acer Intel Core i3 12th Gen 1215U - (16 GB/512 GB SSD/Windows 11 Home) A324-51 Thin and Light Laptop',
 'Acer Aspire 3 Intel Celeron Dual Core - (8 GB/256 GB SSD/Windows 11 Home) A311-45 Thin and Light Lapto...',
 'Lenovo IdeaPad Slim 3 Intel Core i5 12th Gen 12450H - (16 GB/512 GB SSD/Windows 11 Home) 83ER00KSIN Th...']

In [57]:
brand_name = []
for i in soup.find_all('div',class_="KzDlHZ"):
    brand_name.append(i.text)

In [58]:
brand_name

['CHUWI Intel Core i3 10th Gen 10100Y - (8 GB/256 GB SSD/Windows 11 Home) CoreBook X Grey Laptop',
 'CHUWI Intel Core i5 12th Gen 12450H - (16 GB/512 GB SSD/Windows 11 Home) CoreBook X_Pro Laptop',
 'Acer 3 Years Warranty Aspire 3 (2025) Intel Core i3 13th Gen 1305U - (16 GB/512 GB SSD/Windows 11 Home...',
 'Acer Aspire 3 Intel Celeron Dual Core - (8 GB/128 GB SSD/Windows 11 Home) A311-45 Thin and Light Lapto...',
 'Acer Aspire 3 (2025) Intel Core i5 13th Gen 1334U - (16 GB/512 GB SSD/Windows 11 Home) Aspire 3 A325-5...',
 'CHUWI Intel Core i3 12th Gen Intel Core i3-1215U - (12 GB/512 GB SSD/Windows 11 Home) FreeBook 2 in 1 ...',
 'Acer Aspire 3 Intel Core i3 12th Gen 1215U - (8 GB/512 GB SSD/Windows 11 Home) A324-51 Thin and Light ...',
 'HP 15 (2025) AMD Ryzen 3 Quad Core 7320U - (16 GB/512 GB SSD/Windows 11 Home) 15 Thin and Light Laptop',
 'Acer Aspire AMD Ryzen 5 Hexa Core 7430U - (16 GB/1 TB SSD/Windows 11 Home) AS15-42 Thin and Light Lapt...',
 'HP AMD Ryzen 5 Hexa Core 7530U - (8 GB/512 GB SSD/Windows 11 Home) 15-fc0388AU Thin and Light Laptop',
 'Acer Professional AMD Ryzen 3 Quad Core 7th Gen 7330U With Turbo Boost - (16 GB/512 GB SSD/Windows 11 ...',
 'Primebook 2 Max (2025) in-Built AI MediaTek Helio G99 (MT8781) - (8 GB/256 GB/Android 15) PBG9915256#4...',
 'Acer Aspire 3 Intel Celeron Dual Core N4500 - (8 GB/512 GB SSD/Windows 11 Home) A325-45 Thin and Light...',
 'Acer Aspire 3 Intel Celeron Dual Core - (8 GB/512 GB SSD/Windows 11 Home) A311-45 Thin and Light Lapto...',
 'ASUS Vivobook 15, with Backlit Keyboard, Intel Core i3 13th Gen 1315U - (16 GB/512 GB SSD/Windows 11 H...',
 'HP 15 (2024) AMD Ryzen 3 Quad Core 7320U - (8 GB/512 GB SSD/Windows 11 Home) 15-fc0500AU / 15-fc0154AU...',
 "Lenovo IdeaPad Slim 3 Backlit Keyboard with MSO'2024 Intel Core i5 13th Gen 13420H - (16 GB/512 GB SSD...",
 'Lenovo IdeaPad Slim 3 Backlit Intel Core i5 12th Gen 12450H - (16 GB/512 GB SSD/Windows 11 Home) 15IAH...',
 'DELL Inspiron 5440 (2025) Intel Core i3 13th Gen 1305U - (16 GB/512 GB SSD/Windows 11 Home) Inspiron 5...',
 'Samsung Galaxy Book4 Metal Intel Core i3 13th Gen 1315U - (8 GB/512 GB SSD/Windows 11 Home) NP750XGJ-L...',
 'HP Laptop Intel Core i3 13th Gen 1315U - (8 GB/512 GB SSD/Windows 11 Home) 15-fd0129TU / 15-fd0568TU T...',
 'Acer Intel Core i3 12th Gen 1215U - (16 GB/512 GB SSD/Windows 11 Home) A324-51 Thin and Light Laptop',
 'Acer Aspire 3 Intel Celeron Dual Core - (8 GB/256 GB SSD/Windows 11 Home) A311-45 Thin and Light Lapto...',
 'Lenovo IdeaPad Slim 3 Intel Core i5 12th Gen 12450H - (16 GB/512 GB SSD/Windows 11 Home) 83ER00KSIN Th...']

In [91]:
for i in soup.find_all('div',class_="KzDlHZ"):
    print(i.text)

CHUWI Intel Core i3 10th Gen 10100Y - (8 GB/256 GB SSD/Windows 11 Home) CoreBook X Grey Laptop
CHUWI Intel Core i5 12th Gen 12450H - (16 GB/512 GB SSD/Windows 11 Home) CoreBook X_Pro Laptop
DELL Intel Core i3 13th Gen 1305U - (8 GB/512 GB SSD/Windows 11 Home) VN3530XR6N1002ORG1O Thin and Lig...
Lenovo Intel Celeron Dual Core - (4 GB/256 GB HDD/256 GB SSD/DOS) 82C3A00DIH Laptop
DELL inspiron 15 AMD Ryzen 5 Quad Core 7520U - (16 GB/512 GB SSD/Windows 11 Home) Inspiron 3535 Laptop...
CHUWI Intel Core i3 12th Gen Intel Core i3-1215U - (12 GB/512 GB SSD/Windows 11 Home) FreeBook 2 in 1 ...
Lenovo IdeaPad Slim 3 Intel Intel Core i7 13th Gen Core™ i7-13620H, 10C (6P + 4E) / 16T, P-core 2.4 / ...
Lenovo ThinkBook 15 G4 Intel Core i5 12th Gen 1235U - (8 GB/512 GB SSD/Windows 11 Home) TB15 G4 IAP Th...
DELL Intel Core i3 11th Gen 1125G4 - (8 GB/512 GB SSD/Windows 11 Home) Inspiron 5410 2 in 1 Laptop
HP Intel Core i5 13th Gen 1335U - (16 GB/512 GB SSD/Windows 11 Home) 15-hr0001TU Thin and Light Laptop
HP 255 G10 Backlit + FingerPrint (2025) AMD Ryzen 5 Quad Core 7520U - (16 GB/512 GB SSD/Windows 11 Hom...
DELL Inspiron AMD Ryzen 3 Quad Core 5425U - (8 GB/512 GB SSD/Windows 11 Home) Inspiron 3525 Thin and L...
ASUS AMD Ryzen 5 Quad Core - (16 GB/512 GB SSD/Windows 11 Home) E1404FA-NK542WS Laptop
MSI Bravo 15 AMD Ryzen 5 Hexa Core 7535HS - (8 GB/512 GB SSD/Windows 11 Home/4 GB Graphics/AMD Radeon ...
ASUS ROG Strix G16 (2025) with Office 2024 + M365 Basic* AMD Ryzen 9 16 Core 8940HX - (16 GB/1 TB SSD/...
DELL Inspiron AMD Ryzen 3 Dual Core 3250U - (8 GB/256 GB SSD/Windows 11 Home) Inspiron 3525 Thin and L...
DELL G15 AMD Ryzen 7 Octa Core 5800H - (16 GB/512 GB SSD/Windows 10/4 GB Graphics/NVIDIA GeForce RTX 3...
DELL Vostro Intel Core i5 11th Gen i5-1135G7 - (8 GB/512 GB SSD/Windows 10/2 GB Graphics) Vostro 3400 ...
HP Intel Intel Core i3 10th Gen 10110U - (8 GB/512 GB SSD/Windows 10 Home) 15s-DU1516TU Thin and Light...
HP AI PC Intel Core Ultra 5 125H - (16 GB/512 GB SSD/Windows 11 Home) 15-fd1099TU Thin and Light Lapto...
Lenovo Intel Core i3 12th Gen - (8 GB/512 GB SSD/Windows 11 Home) 82RK00VWIN Thin and Light Laptop
HP 255 G10 AMD Ryzen 5 Quad Core 7520U UPTO 4.3Ghz - (8 GB/512 GB SSD/Windows 11 Home) 255 G10 Thin an...
Acer Swift Lite 14 Intel Core Ultra 5 115U - (16 GB/512 GB SSD/Windows 11 Home) SFL14-54M Thin and Lig...
Lenovo V14 AMD Ryzen 3 Dual Core 11th Gen - (8 GB/512 GB SSD/DOS) V14 Gen-4 Business Laptop

In [137]:
import requests
from bs4 import BeautifulSoup
import pandas as pd
import numpy as np
import re

In [138]:
Price =[]
Rating = []
Discount = []
Device_name = []
Brand_name = []
Storage = []
Ram = []
OS = []
Warranties = []
Processors = []

for i in range(1,41):
    url = f"https://www.flipkart.com/search?q=laptop&otracker=search&otracker1=search&marketplace=FLIPKART&as-show=on&as=off&page={i}"
    page = requests.get(url)
    soup = BeautifulSoup(page.text)

    
    for i in soup.find_all("div",class_="tUxRFH"):    #Container
        r = i.find("div",class_="Nx9bqj _4b5DiR")    #Price
        if r:
            Price.append(r.text)
        else:
            Price.append(np.nan)


        r = i.find("div",class_="XQDdHH")              #ratings
        if r:
            Rating.append(r.text)
        else:
            Rating.append(np.nan)


        r = i.find("div",class_="UkUFwK")              #Discount
        if r:
            Discount.append(r.text)
        else:
            Discount.append(np.nan)



        
        text = i.get_text(strip=True)                 #Device name
        # Regex to capture text before " - (" pattern
        match = re.findall(r"Add to Compare(\w+.+)\s\-\s\(", text)
        if match:
            Device_name.append(match[0])
        else:
            Device_name.append(np.nan)


        text = i.get_text(strip=True)                 #Brand name
        match = re.findall(r"^(?:Add to Compare)?(ASUS|Acer|CHUWI|DELL|HP|Lenovo|MSI|Samsung|Ultimus|Infinix|Apple|Primebook|GIGABYTE|MOTOROLA|ZEBRONICS)", text)
        if match:
            Brand_name.append(match[0])
        else:
            Brand_name.append(np.nan)


        text = i.get_text(strip=True)                 #Ram name
        
        match = re.findall(r"Add to Compare\w+.+\s\-\s\((\d+)\s?GB\/", text)
        if match:
            Ram.append(match[0])
        else:
            Ram.append(np.nan)



        text = i.get_text(strip=True)                    # Storage             
        match = re.findall(r"Add to Compare\w+.+\s\-\s\(\d+\s?GB\/(\d+)\s?GB", text)
        if match:
            Storage.append(match[0])
        else:
            Storage.append(np.nan)



        text = i.get_text(strip=True)                               
        match = re.findall(r"(?:Windows\s\d{1,2}(?:\s(?:Home|Pro))?|DOS)", text) #OS
        if match:
            OS.append(match[0])
        else:
            OS.append(np.nan)



    for i in soup.find_all("ul",class_="G4BRas"): 
        text = i.text.strip()                                    # Regex pattern to match warranty information
        warranty_match = re.search(r'\d+\s*(?:Year|Years|Month|Months).*?Warrant[iy].*', text, re.IGNORECASE)
        if warranty_match:
            Warranties.append(warranty_match.group())
        else:
            Warranties.append(np.nan)


   
        text = i.text.strip()
        processor_match = re.search(                                                       # Regex pattern to match processor information
        r'(Intel Core (?:i[3579]|Ultra \d+) Processor \(\d+(?:st|nd|rd|th) Gen\)|'
        r'AMD Ryzen [3579] (?:Quad|Hexa|Octa) Core Processor|'
        r'Qualcomm Snapdragon X Elite Processor)',
        text,
        re.IGNORECASE)
        if processor_match:
            Processors.append(processor_match.group())
        else:
            Processors.append(np.nan)

In [139]:
dict = {
    "Brand_name":Brand_name,
    "Device_name": Device_name,
    "Operating system": OS,
    "Ram(in GB)": Ram,
    "Storage(in GB)": Storage,
    "Price(in ₹)": Price,
    "Discount(in percentages)": Discount,
    "Rating": Rating,
    "Warrenty":Warranties,
    "Processor":Processors
}

In [140]:
df = pd.DataFrame(dict)
df

,Brand_name,Device_name,Operating system,Ram(in GB),Storage(in GB),Price(in ₹),Discount(in percentages),Rating,Warrenty,Processor
0,Samsung,Samsung Galaxy Book4 Metal Intel Core i5 13th ...,Windows 11 Home,8,512,"₹52,500",32% off,4.4,1 Year Manufacturer Warranty for Laptop and 6 ...,Intel Core i5 Processor (13th Gen)
1,CHUWI,CHUWI Intel Core i3 10th Gen 10100Y,Windows 11 Home,8,256,"₹19,990",50% off,4.1,1 Year Onsite Warranty,Intel Core i3 Processor (10th Gen)
2,Acer,Acer Aspire 3 (2025) Intel Core i5 13th Gen 1334U,Windows 11 Home,16,512,"₹41,800",50% off,4.2,3 Years Warranty,Intel Core i5 Processor (13th Gen)
3,Acer,Acer Aspire 3 Intel Celeron Dual Core,Windows 11 Home,8,128,"₹15,990",51% off,3.8,1 Year Warranty,NaN
4,Acer,Acer Aspire 3 Intel Core i3 12th Gen 1215U,Windows 11 Home,8,512,"₹27,990",34% off,4.2,1 Year Domestic Warranty,Intel Core i3 Processor (12th Gen)
...,...,...,...,...,...,...,...,...,...,...
955,HP,HP Intel Core N N200,NaN,8,128,"₹36,999",12% off,3.8,1 Year Onsite Warranty,NaN
956,Lenovo,Lenovo V 15 (2025) Intel Core i5 12th Gen 1235U,Windows 11 Pro,8,512,"₹44,490",47% off,5,NaN,Intel Core i5 Processor (12th Gen)
957,Lenovo,Lenovo IdeaPad Slim 3 Intel Core i5 13th Gen 1...,Windows 11 Home,16,512,"₹54,658",36% off,4.3,NaN,Intel Core i5 Processor (13th Gen)
958,Lenovo,Lenovo V 15 (2025) AMD Ryzen 3 Quad Core 7320U,Windows 11 Home,8,512,"₹28,990",49% off,4.8,1 Year Onsite Warranty,AMD Ryzen 3 Quad Core Processor
959,Infinix,Infinix X1 Slim Series Intel Core i3 10th Gen ...,Windows 11 Home,8,256,"₹35,399",29% off,4.2,1 Year Onsite Warranty,Intel Core i3 Processor (10th Gen)

In [141]:
df.to_csv("Laptops_data_from_flipcart.csv", index=False)

In [142]:
df.head()

,Brand_name,Device_name,Operating system,Ram(in GB),Storage(in GB),Price(in ₹),Discount(in percentages),Rating,Warrenty,Processor
0,Samsung,Samsung Galaxy Book4 Metal Intel Core i5 13th ...,Windows 11 Home,8,512,"₹52,500",32% off,4.4,1 Year Manufacturer Warranty for Laptop and 6 ...,Intel Core i5 Processor (13th Gen)
1,CHUWI,CHUWI Intel Core i3 10th Gen 10100Y,Windows 11 Home,8,256,"₹19,990",50% off,4.1,1 Year Onsite Warranty,Intel Core i3 Processor (10th Gen)
2,Acer,Acer Aspire 3 (2025) Intel Core i5 13th Gen 1334U,Windows 11 Home,16,512,"₹41,800",50% off,4.2,3 Years Warranty,Intel Core i5 Processor (13th Gen)
3,Acer,Acer Aspire 3 Intel Celeron Dual Core,Windows 11 Home,8,128,"₹15,990",51% off,3.8,1 Year Warranty,NaN
4,Acer,Acer Aspire 3 Intel Core i3 12th Gen 1215U,Windows 11 Home,8,512,"₹27,990",34% off,4.2,1 Year Domestic Warranty,Intel Core i3 Processor (12th Gen)